### PR TITLE
Updating multiple dependencies

### LINKED ISSUE #384: Bump nuget dependencies
##### **Overview of the feature request**

Bump nuget dependencies (AutoMapper, Serilog, Scutor, etc ) 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #407: Add generation of gatling performance test
##### **Overview of the feature request**

generation of gatling performance test 

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by EnmanuelReyes**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

Closes #384

### CODE REVIEW

**Comment by EnmanuelReyes** [comment]
I have two tests failing:

Screen Shot 2020-10-03 at 8 07 23 PM

I believe this is happening because the line that's throwing the error is inside the JHipsterNet.Core dependency which is using the old AutoMapper (7.0.0) and I upgraded the version in the generator to 8.0.1.

Can anyone tell me how we are going to proceed?

Should I leave AutoMapper version as it was?
Is there any way to update JHipsterNet.Core's Automapper version?

**Comment by nicolas63** [comment]
In this case two possibility 
- use binding redirect 
- update the core

In your case you can update jhipster.core here (https://github.com/jhipster/jhipster-net)

**Comment by EnmanuelReyes** [comment]
> In this case two possibility
> 
> * use binding redirect
> * update the core
> 
> In your case you can update jhipster.core here (https://github.com/jhipster/jhipster-net)


I created a PR to update JHipsterNet.Core > jhipster/jhipster-net#6

**Comment by nicolas63** [comment]
Thanks, it's merged

**Comment by EnmanuelReyes** [comment]
@nicolas63 I think this PR is ready for merge  🙂

**Review by nicolas63 — APPROVED** [review]
it's ok, thanks

**Pull request merged**
