### PR TITLE
Fix entity generation with service and without DTO

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by nicolas63** [comment]
@ivanmonteiro Can you take a look ? 
@manisi has problem when the application was generated with service but without DTO (see conversation on gitter)

**Comment by manisi** [comment]
> @ivanmonteiro Can you take a look ?
> @manisi has problem when the application was generated with service but without DTO (see conversation on gitter)

new changes (FIX UT) fixed error. need to merge .Thanks

**Comment by nicolas63** [comment]
@manisi it's merged

**Comment by manisi** [comment]
> @manisi it's merged

Thanks to you

**Pull request merged**
