### PR TITLE
Formatted the solution after generation.

### PR DESCRIPTION
**Pull request by vraravam**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vraravam** [comment]
How can I rerun the failed test? I'm not sure why it failed in the first place.

**Comment by vraravam** [comment]
Yes - that is more work.
Also, if there's any syntactic issue in the code, the `dotnet format` command itself will exit with a non-zero exit code. So, your fear about generated code needing verification before formatting isn't necessary imo.

**Comment by vraravam** [comment]
Can this PR be merged please?

**Comment by nicolas63** [comment]
Sorry for the delay, if we add format after the generation we have to add it also when entity was generated (entity-server)

**Comment by vraravam** [comment]
@nicolas63 - do you mean if/when an entity is added mid-way in an existing codebase? Would that not cause other pre-existing files to get formatted? imo - that's not what the user would expect?

**Comment by nicolas63** [comment]
Yes i'am agree but our existing entity file do not respect the format (for exemple namespace brace indentation). It's for this i think a better approach is to correct our generated file before

**Comment by ivanmonteiro** [comment]
> Yes i'am agree but our existing entity file do not respect the format (for exemple namespace brace indentation). It's for this i think a better approach is to correct our generated file before

I'm with @nicolas63 on this one, It would be much better if the templates files were corrected. 
But I understand it would be a lot of work and probably shoud be done in small steps.

**Pull request closed without merging**
