### PR TITLE
Update to new version of JHipster lib, fix other versions to be compa…

### PR DESCRIPTION
**Pull request by kennethlong**
…tible, fix Blazor compiler errors

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Fixes Pagination Issue #980
Fixes Blazor compile errors
Updates to latest version of JHipster-Net library
Updates libraries to be compatible with the library package updates

### CODE REVIEW

**Comment by nicolas63** [comment]
sorry for the delay. Excellent work ! thanks for your contribution. There is still an error on the generation blazor and i think is due to bunit, maybe it's not necessary to update this library ?

**Comment by kennethlong** [comment]
No worries!  Let me take a look at that @nicolas63 - I will see if I can fix those tests.  Looking at other pull requests, those test have been failing intermittently for some time.  Maybe we disable the failing tests if I can't figure out what is wrong, at least until we have time to review all the Blazor stuff.

**Comment by kennethlong** [comment]
@nicolas63 Updated all the Blazor packages and still had those 4 test failing.  Put BUnit back to the preview package version and the test passed.

**Comment by nicolas63** [comment]
> @nicolas63 Should I update JHipster Generator version numbers from 3.4.0 to 3.4.1?

No, it's done automaticaly during the release with release-it

**Comment by kennethlong** [comment]
@nicolas63  What jdl is used to build the entities for the integration tests?  I used the default one that has JobHistory, Employee, etc... and it breaks badly because it has an entity called Task - so it creates a namespace Task which makes all  the async Task stuff ambiguous.

**Comment by nicolas63** [comment]
I use this one (https://github.com/jhipster/jhipster-dotnetcore/blob/main/test-integration/samples/jdl-default/app.jdl), with task modified.

**Comment by kennethlong** [comment]
@nicolas63  Ok, I had to revert Blazorise to the previous version to get those test working.

**Comment by nicolas63** [comment]
All tests is green ! Thanks, and congratulation for your first contribution 🚀 🎊 !

**Comment by ivanmonteiro** [comment]
Nice contribution, congratulations!

**Pull request merged**
