### PR TITLE
Update generator-jhipster to 8.8.0

### PR DESCRIPTION
**Pull request by mshima**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
@mshima This PR has conflicts.

**Review by nicolas63 — APPROVED** [review]

**Comment by mshima** [comment]
@mraible done

**Comment by DanielFran** [comment]
@nicolas63 Any changes you would like to make before realising the new version?
I see some dependabot updates you were working on...

**Comment by nicolas63** [comment]
No we can release now

**Pull request merged**
