### PR TITLE
:construction: add js function to init git folder

### PR DESCRIPTION
**Pull request by tlegrand54**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by tlegrand54** [comment]
merge request to fix issue #1131

**Comment by nicolas63** [comment]
Sorry I forgot to put it back in the issue see last comment here https://github.com/jhipster/jhipster-dotnetcore/pull/1154

You must remove postwriting phase in common generator

**Comment by tlegrand54** [comment]
I think it is ok now

**Comment by nicolas63** [comment]
Yes thanks

**Pull request merged**
