### PR TITLE
Update index.js

### LINKED ISSUE #1135: Rework priorities to use const
##### **Overview of the feature request**

Since this rfc (https://github.com/jhipster/generator-jhipster/blob/main/rfcs/3-jhipster-rfc-unambiguous-priorities.md) the generator-jhipster use constants for priorities and we can also use it in this generator 

So we need to rework all priorities write like this : 

```
 get initializing() {
    return {
      initializingTask() {
        this._sayHello();
      }
    }
  }
```

by 

```
get [INITIALIZING_PRIORITY]() {
    return {
      initializingTask() {
        this.sayHello();
      }
    }
  }
```

##### **Motivation for or Use Case**

the old way was not support in jhipster v8 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vedant-z**
-   Please make sure the below checklist is followed for Pull Requests.
Fixes #1135 
-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by vedant-z** [comment]
@nicolas63 Have I done the expected changes this time or have I made mistake again

Please let me know I will try my best

**Comment by nicolas63** [comment]
No, you should change get initializing or get composing by const define in the main generator like this one [INITIALIZING_PRIORITY]

**Comment by vedant-z** [comment]
So 

get initializing(){
 //no changes here
}
needs to be written like this
get [INITIALIZING_PRIORITY](){
 //no changes here
}

and 

get prompting() ---> get [INITIALIZING_PRIORITY]()

same with get configuring, composing..... , end

Am I on right track

**Comment by nicolas63** [comment]
> So 
> 
> get initializing(){
>  //no changes here
> }
> needs to be written like this
> get [INITIALIZING_PRIORITY](){
>  //no changes here
> }
> 
> and 
> 
> get prompting() ---> get [INITIALIZING_PRIORITY]()
> 
> same with get configuring, composing..... , end
> 
> Am I on right track
> 
> 
> sorry for being annoying but I am bit confused with what needs to be done exactly 
> 
> Sorry for trouble
> 

No problem, in fact the jhipster generator declare const for priorities. In this issue we need to replace hard coded method name by this const a good exemple is here https://github.com/jhipster/generator-jhipster-native/blob/bb9c042f6bc70a26ba8037e951c93dc1d1820983/generators/server/generator.mjs#L24   
You can see one priorities const by method name. 
It's more clear ? Don't hesitate if it's not.

**Comment by vedant-z** [comment]
image

@nicolas63 Hi Sir

Thank you for clarifying once again.

Above I have attached an image of changes I have made, if those are done correctly I will make a PR.

https://github.com/jhipster/jhipster-dotnetcore/compare/main...vedant-z:jhipster-dotnetcore:patch-1

**Comment by nicolas63** [comment]
> image
> 
> @nicolas63 Hi Sir
> 
> Thank you for clarifying once again.
> 
> Above I have attached an image of changes I have made, if those are done correctly I will make a PR.
> 
> https://github.com/jhipster/jhipster-dotnetcore/compare/main...vedant-z:jhipster-dotnetcore:patch-1

Yes it's the right way !

**Comment by vedant-z** [comment]
So should I proceed with PR

**Pull request closed without merging**
