### PR TITLE
Deploy on azure terraform

### LINKED ISSUE #388: [CD] Deploy generated app in Azure App Service
##### **Overview of the feature request**

Deploy generated app to Azure App Service 

sample project 
https://github.com/Azure-Samples/dotnet_core_sample

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by A-5ingh**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Closes #388

### CODE REVIEW

**Review by nicolas63 — APPROVED** [review]
Looks good to me, good job

**Comment by nicolas63** [comment]
Can you add a small test like this https://github.com/jhipster/jhipster-dotnetcore/blob/main/test/dto.spec.js to verify if terraform file is generated please ?

**Comment by A-5ingh** [comment]
@nicolas63 Thanks for all your help.

**Comment by nicolas63** [comment]
Thanks to you !

**Pull request merged**
