### PR TITLE
Added Directory.Build.targets file

### LINKED ISSUE #426: Implement dependabot on generated csproj
##### **Overview of the feature request**

like https://github.com/jhipster/generator-jhipster/pull/12415

We can add dependabot on csproj for bump nuget version 

##### **Motivation for or Use Case**

Reduce time to bump nuget version 

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

fix #426 

@ivanmonteiro @maznag Can you review this ? 

It's big change for the project if i merge this all dependencies are managed by Directory.Build.targets

### CODE REVIEW

**Comment by nicolas63** [comment]
Pros : One file with all dependencies for the solution and we can use variable like AspNetCorePackageVersion,
Allow dependabot to update nuget

Cons : visual studio update package in csproj not in Directory.Build.targets

**Review by ivanmonteiro — COMMENTED** [review]
Since it is unusual to manage package versions this way, It would be nice to have some documentation at Development sub-secton. With information about where to change nuget package versions from now on. If you don't have the time to do it at this PR, create a new issue for documentation.

**Comment by maznag** [comment]
@nicolas63 Thanks Nicolas, it's a very good idea to put all the versions of the packages in one file.

I will test this today and then we can merge.

**Comment by nicolas63** [comment]
> 
> 
> Since it is unusual to manage package versions this way, It would be nice to have some documentation at Development sub-secton. With information about where to change nuget package versions from now on. If you don't have the time to do it at this PR, create a new issue for documentation.

yes I had planned to do it in this issue I wanted to be sure that we all agreed on this change before

**Comment by ivanmonteiro** [comment]
I also agree with this change

**Pull request merged**
