### PR TITLE
Fixed issues with Blazor, DTO and upgrade version

### LINKED ISSUE #1033: Blazor Issue Jhipster-dotnetcore 3.5
I have an issue with generated project Blazor with jhipster-dotnetcore newest version.
Does anyone have the same or only me ?

##### **Overview of the issue**

Cannot run with Blazor. Stuck at loading page.
Console showing this error:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Screenshot_1

##### **Motivation for or Use Case**

Tested ok with jhipster-dotnetcore 3.4 

##### **Reproduce the error**

Used : sample\ jwt-with-blazor-app\ .yo-rc.json

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### LINKED ISSUE #1034: Blazor generated project - User Manager doesn't show - jhipster-dotnetcore 3.4
##### **Overview of the issue**
Screenshot_2
Something wrong with /api/users but it's still ok with angular.

##### **Reproduce the error**

Jhipster-dotnetcore 3.4
jhipster 7.8.1
File used: : sample\ jwt-with-blazor-app\ .yo-rc.json

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by 123445666**
This Pull Request include:
- Updated to jhipster 7.8.1.
- Fixed User Manager (List, Update) with Blazor Project.
- Changed AddSingleton to AddScoped of Services.
- Fixed Bug and Upgrade version of bUnit 1.7.7 (Blazor project).
- Fixed Bug and Upgrade version of BlazoriseVersion 1.0.4 (Blazor project).
- Fixed warning errors.
- Fixed the DTO issue.
- Fixed some others issues ...

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

resolved #1034 
resolved #1033

### CODE REVIEW

**Comment by ivanmonteiro** [comment]
When you mentioned DAO did you mean DTO?

Nice contribution :)

**Comment by 123445666** [comment]
> When you mentioned DAO did you mean DTO?
> 
> Seems that you fixed the DTO issue #787 or am I mistaken?
> 
> By the way, Very nice contribution to the project 👍

Oh yes, Sorry, my mistake :D

**Comment by nicolas63** [comment]
Yes it's a very nice contributions and fix lot of point. @pascalgrimaud maybe we can add a bounty for this ? I think 200 or 300 it's good.

**Comment by pascalgrimaud** [comment]
Bounty added

**Comment by nicolas63** [comment]
Thanks @pascalgrimaud

**Comment by nicolas63** [comment]
fix also #977

**Comment by 123445666** [comment]
Thank you @nicolas63 @pascalgrimaud 
And I have a question. I must write a document report about some works for my study of the Master.
Could I add this project and the community's history in my report ?
Thank you again :D

**Comment by 123445666** [comment]
Hi @pascalgrimaud 
the OpenCollective link 
https://opencollective.com/generator-jhipster/expenses/78101
Thank you.

**Comment by nicolas63** [comment]
> Thank you @nicolas63 @pascalgrimaud 
> And I have a question. I must write a document report about some works for my study of the Master.
> Could I add this project and the community's history in my report ?
> Thank you again :D

Yes you can, it's a good thing to talk about the project.

**Comment by pascalgrimaud** [comment]
@123445666 : approved

**Pull request merged**
