### PR TITLE
Fix Error when using migrations

### LINKED ISSUE #475: Error when using migrations
##### **Overview of the issue**

User @javadjahangiriniopdc reported the following error:

```
Due to the upgrade to version 5 now gives the following error when migrating
Error CS1061 'ModelBuilder' does not contain a definition for 'UseIdentityColumns' and no accessible extension method 'UseIdentityColumns' accepting a first argument of type 'ModelBuilder' could be found (are you missing a using directive or an assembly reference?) Crm.Infrastructure C:\Users\jahangiri\source\repos\Crm\src\Crm.Infrastructure\Migrations\20201126065627_InitioalCreator.Designer.cs
```

And suggested to add the package Microsoft.EntityFrameworkCore.SqlServer to the project Infrastructure.

As a note: 

When I released the EF 5 version of this project, I noticed that I had to add a direct package reference to EF 5 to the infrastrtucture project, otherwise it would not compile. Maybe it is related to that, as the only fix I found at the time was to add the EF 5 package reference.

When I have some spare time I'll try to reproduce this issue and provide a fix, which should be simple. Here is the infrastructure csproj: 
https://github.com/jhipster/jhipster-dotnetcore/blob/main/generators/server/templates/dotnetcore/src/Project.Infrastructure/Project.csproj.ejs

But if anyone else is willing to work on this, just add a comment on this issue.

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ivanmonteiro**
Fix #475

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Review by nicolas63 — APPROVED** [review]
Thanks for your reactivity. I will release a new version to integrate this bug fix

**Comment by nicolas63** [comment]
@javadjahangiriniopdc Can you test it ?

**Comment by nicolas63** [comment]
@ivanmonteiro no feedbrack since 2 days i think we can merge this

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro no feedbrack since 2 days i think we can merge this

I agree. 

What was changed was mostly just moving the EF Core package references from the API project to the Infrastructure project.

On my manual tests it worked fine.

**Pull request merged**
