### PR TITLE
Upgrade to JHipster 8

### PR DESCRIPTION
**Pull request by mshima**
Fixes https://github.com/jhipster/jhipster-dotnetcore/issues/1340

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by nicolas63** [comment]
Wow, it's an enormous rework! A heartfelt thank you for your assistance; I couldn't have done it without you. If you need anything you can ask me

**Comment by mshima** [comment]
@nicolas63 I probably removed the release dependencies and some files may need some adjusts.
JHipster v8 migration is big enough, I may readd I you need so in a follow up PR.

I've noticed that the pagination seems not to be compatible. jhipster uses a link header.
Let me know if you have any doubt.

**Comment by nicolas63** [comment]
i have one question, when i run jhipster-dotnet i get this error : 
`
WARNING! Could not retrieve packagePath of blueprint 'generator-jhipster-jhipster-dotnetcore'
WARNING! Could not retrieve version of blueprint 'generator-jhipster-jhipster-dotnetcore'
ERROR! ERROR! Some blueprints were not found jhipster-jhipster-dotnetcore, you should install them manually
Error: Some blueprints were not found jhipster-jhipster-dotnetcore, you should install them manually
`
I have just clone your fork, run npm link
I have miss something ?

**Comment by mshima** [comment]
@nicolas63 I forgot about this, rename the folder from jhipster-dotnetcore to generator-jhipster-dotnetcore and link again.
Please fill an issue at generator-jhipster so I can remember.

**Comment by mshima** [comment]
Oh I think it’s not necessary to fill a bug, just a cli adjusts.

**Comment by mshima** [comment]
To generate a sample run `jhipster-dotnetcore generate-sample --withEntities` at a new folder.
The generate-sample generator is located at `.blueprint` folder.

**Comment by nicolas63** [comment]
> @nicolas63 I forgot about this, rename the folder from jhipster-dotnetcore to generator-jhipster-dotnetcore and link again. Please fill an issue at generator-jhipster so I can remember to take a look.

it's good after the rename, i have open the issue : https://github.com/jhipster/generator-jhipster/issues/23694

**Pull request merged**
