### PR TITLE
Jhipster 7.6 

### PR DESCRIPTION
**Pull request by 123445666**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mshima** [comment]
Need to upgrade generator-jhipster here too.
https://github.com/jhipster/jhipster-dotnetcore/blob/d4083766643f9d911a10019fcae04a275868370e/test-integration/scripts/00-install-all-jhipster.sh#L9

 yo is not required and should be dropped :
https://github.com/jhipster/jhipster-dotnetcore/blob/d4083766643f9d911a10019fcae04a275868370e/test-integration/scripts/00-install-all-jhipster.sh#L11-L15

**Comment by mshima** [comment]
It’s possible to install generator-jhipster version from package.json.
Something like https://github.com/jhipster/generator-jhipster/blob/eda94cfc0b90eaeb211d556308e879e603639c6c/test-integration/scripts/00-init-env.sh#L98.
And migrate to a custom cli when v7.7.0 is released. To avoid version conflicts.

**Comment by nicolas63** [comment]
oh yes, thanks @mshima. 
@123445666  i have see you location if you want discuss with me you can contact me in private on gitter (https://gitter.im/nicolas63)

**Comment by 123445666** [comment]
Thanks for your help. @mshima @nicolas63 . I'm still working on it.

**Comment by nicolas63** [comment]
Very nice work @123445666 and congratulation for your first contribution 🚀 🎊  !
 @pascalgrimaud  Maybe we can add a bug bounty for the migration from jhiptser 7.1 to 7.6 on the blueprint done by @123445666

**Comment by pascalgrimaud** [comment]
Done :-)

**Comment by nicolas63** [comment]
thanks @pascalgrimaud , @123445666 you can claim the bounty => https://www.jhipster.tech/bug-bounties/

**Comment by 123445666** [comment]
Oh, Thank you so much for the bug bounty @nicolas63 @pascalgrimaud . I haven't finished it yet, it still shows many warning when run lint with the generated project. I'll fix it in next step and improve my code too. Thank you.

**Comment by pascalgrimaud** [comment]
@123445666 : don't forget to comment this pull request with the OpenCollective link, once you submit the expense. So I can be sure that you're the same person ;)

**Comment by 123445666** [comment]
@pascalgrimaud this one, right ? :D  https://opencollective.com/generator-jhipster/expenses/64285
Thank you.

**Comment by pascalgrimaud** [comment]
@123445666 : :approved :)

**Pull request merged**
