### PR TITLE
update to generator-jhipster v6.8.0

### PR DESCRIPTION
**Pull request by maznag**
update to generator-jhipster v6.8.0

### CODE REVIEW

**Comment by nicolas63** [comment]
There are build errors, can you verify ?

**Comment by maznag** [comment]
Timeout !!

`npm ERR! errno 1
npm ERR! generator-jhipster-dotnetcore@0.3.0 test:unit: `mocha --timeout 200000 --slow 0 --reporter spec "test/client.spec.js" "test/entity.spec.js" "test/server.spec.js" "test/spring-controller.spec.js" "test/spring-service.spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generator-jhipster-dotnetcore@0.3.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-03-12T08_32_46_269Z-debug.log
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.`

Question: why we have spring controller in dotnet blueprint ?

**Comment by maznag** [comment]
the 'npm run test' runs without problems on my machine.

----

`run `npm audit fix` to fix them, or `npm audit` for details
      ✓ it works

  Subgenerator entity of dotnetcore JHipster blueprint
    Sample test
      ✓ it works

  Subgenerator server of dotnetcore JHipster blueprint
    Sample test
      ✓ it works

  Subgenerator spring-controller of dotnetcore JHipster blueprint
    Sample test
      ✓ it works

  Subgenerator spring-service of dotnetcore JHipster blueprint
    Sample test
      ✓ it works


  5 passing (1m)

The template "Solution File" was created successfully.`

**Comment by nicolas63** [comment]
It's not a timeout ( ``` Error: Cannot find module 'grouped-queue/lib/subqueue' ``` )

**Pull request merged**
