### PR TITLE
Namespace refactoring

### PR DESCRIPTION
**Pull request by ivanmonteiro**
Domain and Dto namespace refactoring.
This a pre-requisite to split code into separate projects
for dto and service issues (#274 and #275 respectively).

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ivanmonteiro** [comment]
I did this as a separate PR to try to not pollute too much the other PR

@nicolas63  Please let me know if you want a different namespace naming

**Comment by nicolas63** [comment]
It's ok for me, I merge this PR before DTO PR ?

**Comment by ivanmonteiro** [comment]
> It's ok for me, I merge this PR before DTO PR ?

yes, please

**Comment by nicolas63** [comment]
done

**Pull request merged**
