### PR TITLE
update to dotnet core 3.1 version

### PR DESCRIPTION
**Pull request by maznag**
- Update to dotnet core 3.1
- Update to latest Nuget packages
- Remove obsolete interface IHostingEnvironment

Related issue #43

### CODE REVIEW

**Comment by danielpetisme** [comment]
Thank you for the PR (and sorry for the delayed answer)

@nicolas63 could you help me to review this PR please.

**Comment by nicolas63** [comment]
Yes with pleasure

**Comment by nicolas63** [comment]
Looks good to me.

**Comment by sergrdz** [comment]
The docker file is not updated to dotnet core 3.1 version

/generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs

**Pull request merged**
