### PR TITLE
Fix swagger and indentation in startup.cs

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by nicolas63** [comment]
@ivanmonteiro can you try this fix ?

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro can you try this fix ?

I just tried your changes and it fixed swagger on the server side.

The only issue I found was that when using the client application:
go to Administration menu > API Docs

It shows a sample documentation (Swagger Petstore 1.0.5) not the generated one.

**Comment by nicolas63** [comment]
yes, but this endpoint has never work. I will merge this PR and open an issue for this

**Comment by ivanmonteiro** [comment]
thank you @nicolas63

**Pull request merged**
