### PR TITLE
Mongo identity and net6 startup

### LINKED ISSUE #803: Handle users/accounts with Mongo
##### **Overview of the feature request**

After MongoDB support being added with #717, which allows to handle entities with MongoDB, the main missing feature is to handle Claims/Users/Accounts with Mongo. This could be done with [AspNetCore.Identity.Mongo](https://github.com/matteofabbri/AspNetCore.Identity.Mongo).

##### **Motivation for or Use Case**

This feature would allow to generate applications with Mongo that doesnt need a second in-memory database (SQLite) in order to manage Users/Account.

##### **Related issues or PR**

#96

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

fix #803, #96 ,#1124

### CODE REVIEW

**Comment by nicolas63** [comment]
@enzo-ae everything work now, thanks you for your hudge work on this feature. And I'm sorry I couldn't help you earlier 

@pascalgrimaud they are two big feature on this PR it's possible to add two bounty ? one of 500$ for @enzo-ae and one of 100 for me ?

**Comment by pascalgrimaud** [comment]
Done, just claim it when it's merged and ping me
Some conflict to solve before :-D

**Comment by nicolas63** [comment]
I just merge another PR, I am in the process thank you very much @pascalgrimaud

**Comment by nicolas63** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/97453
@enzo-ae you can also claim your bounty

**Comment by pascalgrimaud** [comment]
@nicolas63 : approved

**Pull request merged**
