### PR TITLE
Bump generator-jhipster from 7.8.1 to 7.9.3

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by nicolas63** [comment]
I try to update to the latest version of jhipster and i have few error during the cypress generation phase @mshima can you help me ?

**Comment by nicolas63** [comment]
this error is 

```An error occured while running jhipster-dotnetcore:cypress#writeFiles
ERROR! Template file src/JhipsterSampleApplication/ClientApp/test/cypress/.eslintrc.json was not found at /home/runner/work/jhipster-dotnetcore/jhipster-dotnetcore/generators/cypress/templates,/home/runner/work/jhipster-dotnetcore/jhipster-dotnetcore/node_modules/generator-jhipster/generators/cypress/templates
```

**Comment by mshima** [comment]
Sure, it’s a bug at the generator-jhipster, I am thinking if there is a way to workaround. A new release may be required.

**Comment by nicolas63** [comment]
@mshima any news ?

**Comment by mshima** [comment]
@nicolas63 https://github.com/jhipster/generator-jhipster/pull/19955.

I created https://github.com/nicolas63/jhipster-dotnetcore/pull/2, but I don't know the reason for the failures.
I will try to debug later.

**Comment by nicolas63** [comment]
Thank you

**Pull request closed without merging**
