### PR TITLE
Deploy generated app in Heroku

### LINKED ISSUE #389: [CD] Deploy generated app in Heroku
##### **Overview of the feature request**

Deploy generated app in Heroku

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ivanmonteiro**
Fix #389

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ivanmonteiro** [comment]
The SonarCloud Code Analysis is  failing due to security reasons, but the code lines that it is complaining about, are exact copies of lines present at the main jhipster generator. 

In a web project shell injection would be a really serious issue,  but the heroku sub-generator is used only at the commnad line interface. So I think it is not a serious security concern since ChildProcess.exec is used only at the heroku sub-generator.

@nicolas63 could you take a look at the SonarCloud Code Analysis?

**Comment by nicolas63** [comment]
@ivanmonteiro yes this code is not analyze by sonar in the main generator
Maybe you can replace 
```
ChildProcess.exec
```

by something like this 
```
this.spawnCommandSync('npm', ['--prefix', `${constants.SERVER_SRC_DIR}${this.mainClientDir}`, 'run', 'cleanup']);
```

or use shelljs like in dotnet.js

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro yes this code is not analyze by sonar in the main generator
> Maybe you can replace
> 
> ```
> ChildProcess.exec
> ```
> 
> by something like this
> 
> ```
> this.spawnCommandSync('npm', ['--prefix', `${constants.SERVER_SRC_DIR}${this.mainClientDir}`, 'run', 'cleanup']);
> ```
> 
> or use shelljs like in dotnet.js

Thanks, I will work on it soon

**Comment by ivanmonteiro** [comment]
Regarding database connection strings:

When using the database addons of Heroku, it stores an environment variable with the database connection with this special format:
`DATABASE_URL=mysql://user:password@server-url:3306/db-name`
Unfortunately, we cannot use this database url directily.

It seems that we have two options:

- Create a new config file for Heroku (appsettings.Heroku.json?)
The values from DATABASE_URL could be extracted using a regular expression and a new appsettings.Heroku.json file would be created with the connection string with the proper values.

- Or create a new environment variable
Create an environment  variable (ConnectionStrings:AppDbContext) to override existing connection string. The values from DATABASE_URL woud need to be extracted through a regular expression and a new environment variable would need to be created on heroku:
 `heroku config:set ConnectionStrings:AppDbContext='Server=server-url;Port=3306;Database=db-name;User=user;Password=password;'`

@nicolas63 @maznag Which option do you think is better?

**Comment by maznag** [comment]
Or simply modify `DatabaseConfiguration` to get the connection string from the ENV variable as follow ==> OPTION 3

```
string connection = null;

// Get the connection string from the ENV variable, for example DATABASE_URL=mysql://user:password@server-url:3306/db-name
string dataBaseConnectionUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

if (!string.IsNullOrEmpty(dataBaseConnectionUrl))
{
    //  Parse the connection string
    var databaseUri = new Uri(dataBaseConnectionUrl);

    string db = databaseUri.LocalPath.TrimStart('/');
    string[] userInfo = databaseUri.UserInfo.Split(':', StringSplitOptions.RemoveEmptyEntries);

    connection = $"Server={databaseUri.Host};Database={db};Port={databaseUri.Port};User Id={userInfo[0]};Password={userInfo[1]};Integrated Security=true;Pooling=true;";
}
// OR Get the connection string from appsettings
else
{                
    connection = configuration.GetConnectionString("AppDbContext");
}
```

**Comment by nicolas63** [comment]
@ivanmonteiro i'm agree with @maznag i think is the good solution.

Just a precision in the program.cs we load env variables 
```
 return new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{environment}.json", true)
                .AddEnvironmentVariables()
                .Build();
```
so i think you can get database url from configuration rather than  Environment.GetEnvironmentVariable("DATABASE_URL");

**Pull request merged**
