### PR TITLE
Fix multiple many-to-many relationships in JDL

### LINKED ISSUE #228: Problem with multiple many-to-many relationships in JDL
##### **Overview of the issue**

When defining multiple many-to-many relationships with jdl, the Join Entity class is created with the same contents of the first relationship, for all relationships. This causes complier error because the same class is created again and again.

##### **Reproduce the error**

Create a jdl with two or more many-to-many relationships and generate the files with jhipster

This creates three classes implementing IJoinedEntity for the many-to-many relationships, but with exactly the same source code for them.

  <details>
  <summary>JDL definitions</summary>
  <pre>
entity Product {
    name String
}

entity Category {
    name String
}

entity Kit {
    name String
}

relationship ManyToMany {
    Order{products(name)} to Product{orders}
    Category{products(name)} to Product{categories}
    Kit{products(name)} to Product{kits}
}

relationship ManyToOne {
    Kit{usuario(login)} to User
    Produto{usuario(login)} to User
}
  </pre>
  </details>

##### **Related issues**

Might be related to #224

##### **JHipster configuration**

Using master version of dotnet generator

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nicolas63**
-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

fix #228

### CODE REVIEW

**Comment by nicolas63** [comment]
@ivanmonteiro can you try this branch ? I think it solve your issue #228

**Comment by ivanmonteiro** [comment]
> @ivanmonteiro can you try this branch ? I think it solve your issue #228

Yes, I'll get back to you soon. Is it the master branch on your fork?

**Comment by nicolas63** [comment]
> 
> 
> > @ivanmonteiro can you try this branch ? I think it solve your issue #228
> 
> Yes, I'll get back to you soon. Is it the master branch on your fork?

Yes

**Comment by ivanmonteiro** [comment]
I updated the jdl to add the many-to-one relationship my entities have with User entity. It might be related to why the joinentity files are not generated correctly.

  <details>
  <summary>JDL definitions</summary>
  <pre>
entity Product {
    name String
}

entity Category {
    name String
}

entity Kit {
    name String
}

relationship ManyToMany {
    Order{products(name)} to Product{orders}
    Category{products(name)} to Product{categories}
    Kit{products(name)} to Product{kits}
}

relationship ManyToOne {
    Kit{usuario(login)} to User
    Produto{usuario(login)} to User
}
  </pre>
  </details>

Just tested with your code and:
-table name is empty
[Table("")]

the interface implementation is picking up the wrong entities. User is a many-to-one realationship of Kit and User. It is supposed to be Kit and Produto.
public class  : IJoinedEntity<User>, IJoinedEntity<Kit> {

Also, the code is generating wrong properties/getter/setter.

`

    [Table("")]
    public class  : IJoinedEntity<User>, IJoinedEntity<Kit> {
        public long UserId { get; set; }
        public User User { get; set; }
        User IJoinedEntity<User>.Join {
            get => User;
            set => User = value;
        }

        public long KitId { get; set; }
        public Kit Kit { get; set; }
        Kit IJoinedEntity<Kit>.Join {
            get => Kit;
            set => Kit = value;
        }

`

**Comment by ivanmonteiro** [comment]
@nicolas63 check JoinEntity.cs.ejs file, I might be wrong but I think that the code to pick up the owner/owend entities is actually picking up the wrong owner/owned entities from other relationships (see my previous message)

**Comment by nicolas63** [comment]
Thank you for your feedback, i will try to solve this tomorrow.

**Comment by ivanmonteiro** [comment]
> Thank you for your feedback, i will try to solve this tomorrow.

You're welcome. 
I'm not sure how this templating engine works but it might be related to the following code on JoinEntity.cs.ejs:

```

let idx = 0;
relationship = relationships[idx];
joinEntityTableName = relationships[idx].joinEntityNameSnakeCased;
joinEntityClassName = relationships[idx].joinEntityNamePascalized;
if (relationships[idx].relationshipType === 'many-to-many') {
    relationships[idx].joinEntityGenerated = true;
    ownerSide = relationships[idx].ownerSide;
}

```

Because it is picking the index 0 of relationships, which coincidently is on my case the many-to-one relationship on .jhipster/Kit.json
```


 "relationships": [
    {
      "relationshipType": "many-to-one",
      "otherEntityName": "user",
      "otherEntityRelationshipName": "kit",
      "relationshipName": "usuario",
      "otherEntityField": "login"
    },
    {
      "relationshipType": "many-to-many",
      "otherEntityName": "produto",
      "otherEntityRelationshipName": "kits",
      "relationshipName": "produtos",
      "otherEntityField": "nome",
      "ownerSide": true
    }
  ],


```

**Comment by nicolas63** [comment]
Maybe you can try to revert my changes in joinentity.ejs the important changes are in files.js.

**Comment by ivanmonteiro** [comment]
> Maybe you can try to revert my changes in joinentity.ejs the important changes are in files.js.

Reverting the joinentity.ejs file did generate the files correctly

**Comment by nicolas63** [comment]
thank you @ivanmonteiro, i have reverted the joinentity.ejs changes. 
All it's ok for you ?

**Comment by ivanmonteiro** [comment]
> thank you @ivanmonteiro, i have reverted the joinentity.ejs changes.
> All it's ok for you ?

@nicolas63  The joinentity files are generating correctly but integration tests are failing.

**Comment by ivanmonteiro** [comment]
> thank you @ivanmonteiro, i have reverted the joinentity.ejs changes.
> All it's ok for you ?

I have not yet tested your updates to the branch.
Could you please take a look on the failing CI integration tests?

**Comment by ivanmonteiro** [comment]
Just tested your new changes and it worked. Thank you @nicolas63

**Comment by nicolas63** [comment]
nice, i merge it

**Pull request merged**
